/*
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 *  limitations under the License.
 */
// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.parworks.androidlibrary.ar;

public class OverlayBuilder extends OverlayBuilderBase<OverlayBuilder> {
	public static OverlayBuilder overlay() {
		return new OverlayBuilder();
	}

	public OverlayBuilder() {
		super(new OverlayData());
	}

	public OverlayData build() {
		return getInstance();
	}
}

class OverlayBuilderBase<GeneratorT extends OverlayBuilderBase<GeneratorT>> {
	private OverlayData instance;

	protected OverlayBuilderBase(OverlayData aInstance) {
		instance = aInstance;
	}

	protected OverlayData getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withVertices(float aValue) {
		instance.setVertices(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withName(String aValue) {
		instance.setName(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDescription(String aValue) {
		instance.setDescription(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withBaseImageId(String aValue) {
		instance.setBaseImageId(aValue);

		return (GeneratorT) this;
	}
}
